### ISSUE TITLE
Error in receipt for instance without data.

### ISSUE THREAD

**Issue by JohanGuntherKrogevoll** [Altinn/altinn-receipt#53] opened 2022-11-03 14:22 UTC
### Description of the bug

I tried to configure a altinn3-app to delete all data but keep the instance, so that end user can see that form has been sent but not access the data. This was the result:

![Kapture 2022-11-03 at 14 07 44](https://user-images.githubusercontent.com/66003225/199744532-626f30d6-b25d-4a4d-a5e9-4259bcc57316.gif)

### Steps To Reproduce

1. Configure an apps applicationmetadata.json with `"appLogic": {"autoDeleteOnProcessEnd": true}` on all `datatypes` and `"autoDeleteOnProcessEnd": false` on the instance-level. 
2. Submit the form. 
3. Try to navigate to the receipt in archive. 

### Additional Information

[slack-link](https://altinn.slack.com/archives/C02ESDSC929/p1667481073160989)

**Comment by vgr** [comment] 2022-11-08 14:33
Have reproduced it locally with an app where
- all the datatypes have `"appLogic": { "autoDeleteOnProcessEnd": true }`, and 
- the application has `"autoDeleteOnProcessEnd": false `

The error message locally was: `Uncaught typeerror applicationMetaDataUtils_1.getCurrentTaskData is undefined`

The problem is that the code that attempts to find the timestamp for when it was submitted only checks that the `instance.data` array exists, but it will attempt to access a member even if length is 0. This is fixed by simply checking the array length.

The next question is which timestamp is the most correct to fall back on.
<table>
<tr>
	<td>data 
	<td>timestamp from a test instance
	<td>comment
<tr>
	<td> instance.data[x].lastChanged
	<td>"2022-11-08T14:04:07.1433055Z"
	<td> This is used today
<tr>
	<td> instance.status.archived
	<td>"2022-11-08T14:04:07.5595883Z"
	<td> I think this would be correct to use, as long as this is set for every instance that has an receipt.
<tr>
	<td> instance.lastChanged
	<td> "2022-11-08T14:04:08.1398807Z"
	<td> This could be a good alternative fallback, but not sure about correctness if state changes.
<tr>
	<td> instance.process.ended
	<td> "2022-11-08T14:03:36.2491704Z"
	<td> Don't think this is the correct fallback.
</table>

**Comment by SandGrainOne** [comment] 2022-11-08 14:41
I also think that the instance.status.archived timestamp is the best one.

But I wonder why it was using data[x].lastChanged in the first place. Storage have logic checking dates from data elements because they might have been updated later than the last change to the instance, but this can't be true once the instance has been archived.

**Comment by acn-sbuad** [comment] 2022-11-16 09:41
Verified in AT23 ![image.png](https://images.zenhubusercontent.com/5c8f655333fd990b927f5ea1/d4ac9c44-5b1a-49cc-ae0f-1aab07564668)

**Closed** 2022-11-16 09:42 UTC
Labels: kind/bug
