### ISSUE TITLE
Cannot communicate with Localtest when running in Docker container

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-receipt#6] opened 2022-08-12 07:26 UTC
### Description of the bug

Receipt does not run successfully in a docker container when running on a local machine because the communication with localtest fails.

### Steps To Reproduce

1. Instantiate an app in localtest and complete process
2. Modify url to go towards receipt e.g `http://altinn3local.no/receipt/512345/6ab305f9-8d7a-48bd-8ae7-8576a4e0da01`
3. See error

**Comment by annerisbakk** [comment] 2024-02-02 07:07
@acn-sbuad Er denne fremdeles aktuell?

**Comment by acn-sbuad** [comment] 2024-02-02 07:50
> @acn-sbuad Er denne fremdeles aktuell?

Det har ikke vært gjort noen tiltak fra vår side for å løse dette, så det vil jeg tro.

**Comment by codemascot** [comment] 2024-03-11 08:44
@SandGrainOne Should we consider it done as this one got merged? 🤔  https://github.com/Altinn/altinn-receipt/issues/253

**Comment by SandGrainOne** [comment] 2024-03-11 08:54
@codemascot I have only tested with both Receipt and Localtest as containers in Podman. I didn't consider testing with Receipt running locally.

**Comment by olebhansen** [comment] 2024-07-09 14:16
@SandGrainOne : Can you please check and close if it was solved in #253 ?

**Comment by SandGrainOne** [comment] 2024-07-10 10:59
@olebhansen We don't have instructions for running Receipt outside of docker and I'm not getting it to work. The readme say the following on the matter: `The platform receipt component need to be run in Docker.` 

To me this means that the basis of the issue is invalid. We should create a new issue for investigating how to run Receipt locally.

**Comment by olebhansen** [comment] 2024-07-15 08:51
Closing

**Closed by olebhansen** 2024-07-15 08:51 UTC
Labels: kind/bug, tm/no
